export const types = {
  POST_BASE: "POST_BASE",
  GET_BASE: "GET_BASE",
  PUT_BASE: "PUT_BASE",
  DEL_BASE: "DEL_BASE",
  DEL_ALL: "DEL_ALL",
  MODAL_SHOW_HIDDEN :"MODAL_SHOW_HIDDEN",
  MODAL_CHANGE :"MODAL_CHANGE" ,
  LOADING:"LOADING"
};
